package main

const (
	P_UNKNOWN = 0
	P_TRUE = 1
	P_FALSE = 2
)

func PalindromeStatusToBool(status int) *bool {
	var out *bool

	if status == P_UNKNOWN {
		out = nil
	} else if status == P_TRUE {
		t := true
		out = &t
	} else {
		f := false
		out = &f
	}

	return out
}

// pretend this function takes a long time to run
func StringIsPalindrome(s string) bool {
	// this was entirely generated by CoPilot
	for i := 0; i < len(s) / 2; i++ {
		if s[i] != s[len(s) - i - 1] {
			return false
		}
	}

	return true
}